data_generation:
  anomaly_rate: 0.03
  base_seasonal_period: 24
  noise_level: 0.15
  secondary_seasonal_period: 168
  trend_coefficient: 0.002
detection:
  ewma_alpha: 0.15
  isolation_forest_samples: 256
  robust_zscore_threshold: 3.5
  window_size: 150
  z_score_threshold: 3.5
visualization:
  max_points: 1000
  update_interval: 50
